project:
  type: website

execute:
  freeze: false
  project:
    type: website
    # Place timing outputs in the default site folder; this inherits other
    # settings from the base `_quarto.yml`.
    output-dir: _site

  execute:
    # ensure we actually run code to measure time
    eval: true
    # disable freeze and cache so timings reflect full cost
    freeze: false
    cache: false
    # show messages so logs are informative
    echo: true
    message: true
    warning: true
    error: true

  format:
    html:
      keep-md: true

  # Timing profile: disables caching and freezing so each render runs for
  # an accurate timing measurement. Use with: `quarto render --profile timing <file>`
  cache: false
