---
title: "Data Science for Transport Planning: 2 day course"
---

## Course Overview

Based on demand, we're organising a 2-day course teaching modern data science skills for transport planning, focussed on transport planning practitioners.
This course will take place on the 18th and 19th of September.

<!-- ## Learning Objectives

- Understand the role of data science in transport planning.
- Learn how find, import, clean, and analyze transport data.
- Develop skills in data visualization and reporting. -->

## Prerequisites

- Experience with transport planning concepts and datasets, such as origin-destination data and route networks.
- Basic programming skills in R, Python or similar.
- A laptop with R and RStudio (recommended) or a Python distribution such as Anaconda and an editor such as VS Code or Jupyter Notebook set-up.

## Schedule

### Day 1: Introduction to R/RStudio

- 10:00 - 11:00 Introduction to Data Science for Transport Planning
- 11:00 - 12:30 Finding, importing and cleaning transport datasets
    - Origin-destination datasets
    - OpenStreetMap and Ordnance Survey OpenRoads datasets
    - Stats19 road safety data
- 12:30 - 13:30: lunch
- 13:30 - 15:00 Origin-destination data analysis
- 15:00 - 15:15 break and refreshments
- 15:15 - 17:00 Routing and route network analysis
  - This will cover setting up an OpenTripple API and using it to calculate routes and distances using GTFS data.

### Day 2:

Course times each day:

- 09:00 - 10:45 spatio-temporal data
  - Demonstration of open-access OD data with hourly resolution
  - Demonstration with stats19 data for road safety analysis
- 10:45 - 11:15 break and refreshments
- 11:15 - 12:30 OD Transport data visualisation
- 12:30 - 13:30 lunch
- 13:30 - 15:00 Best practices for data science in transport planning
  - Version control with Git and GitHub
  - Reproducible research with Quarto
- 15:00 - 16:00 Advanced topics
  - Visualising large datasets
  - Route network integration
      - We'll present ways to join different networks, e.g. OSM and OS networks
  - Deploying your work as web applications

## Registration

TBC.

We look forward to seeing you at the course!