[project]
channels = ["conda-forge"]
description = "Add a short description here"
name = "tds"
platforms = ["win-64", "linux-64", "osx-64"]
version = "0.1.0"

[dependencies]
quarto = "*"
r-base = "*"
r-irkernel = "*"
r-tidyverse = "*"
r-sf = "*"
r-terra = "*"
r-quarto = "*"
r-nycflights13 = "*"
r-remotes = "*"
r-DT = "*"
r-reticulate = "*"
r-spData = "*"
r-pak = "*"
r-geosphere = "*"

[tasks]
simple = "echo This is a simple task"
install_r = { cmd="Rscript install.R" }
install_py = { cmd = "python3 -m pip install --user -r requirements.txt" }
install_all = { cmd = "python3 -m pip install --user -r requirements.txt && Rscript install.R" }