[project]
channels = ["conda-forge"]
description = "Add a short description here"
name = "tds"
platforms = ["win-64", "linux-64", "osx-64"]
version = "0.1.0"

[dependencies]
jupyter = "*"
jupyter-cache = "*"
geopandas = "*"
matplotlib = "*"
shapely = "*"
seaborn = "*"
quarto = "*"
r-base = "*"
r-irkernel = "*"
r-tidyverse = "*"
r-sf = "*"
r-quarto = "*"
r-nycflights13 = "*"
r-remotes = "*"
r-DT = "*"
r-reticulate = "*"
r-spData = "*"
r-pak = "*"

[tasks]
simple = "echo This is a simple task"
install_r = { cmd="Rscript install.R"}