[project]
channels = ["conda-forge"]
description = "Add a short description here"
name = "TDStests"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
jupyter = "*"
jupyter-cache = "*"
geopandas = "*"
matplotlib = "*"
shapely = "*"
seaborn = "*"
quarto = "*"
r-base = "*"
r-irkernel = "*"
r-tidyverse = "*"
r-sf = "*"
r-quarto = "*"
r-nycflights13 = "*"
r-remotes = "*"
r-DT = "*"
r-reticulate = "*"
r-spData = "*"
r-pak = "*"