---
bibliography: ../tds.bib
output: github_document
---

<!-- message to students, 2021-01-28 -->

```{r, include=FALSE}
library(tidyverse)
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```

# Session plan for Practical 4

This is will be the 4th and penultimate practical session in the TDS module.
The final practical session on coursework will be **in 2 months time, on 28th April**.

Session content: https://github.com/ITSLeeds/TDS/blob/master/practicals/od-route-analysis.md

The session will be structured as follows:

- Analysis of zone data and the tidyverse (1 hour)

- Analysis of OD level data (1 hour)

- Brainstorming ideas for the coursework (1 hour)

  - Read through topic ideas here: https://github.com/ITSLeeds/TDS/blob/master/coursework-template.md#031-topics 

  - Which are your favourite, and why? Which alternative topics could you think of?  

  - Think about a topic you would like to work on 

  - Make a start on your 2 page project plan: deadline for submission is **in less than 1 month, 18th March**
  
  - Which of the datasets presented [here](https://github.com/ITSLeeds/TDS/blob/master/coursework-template.md#032-datasets) are of most interest to you? Are there any other datasets you would like to explore for this session?
