---
title: "Coursework submission for Transport Data Science (TRAN5340M): resit guidance"
# subtitle: "Enter your own title here (e.g. Exploring open transport data: a study of the Isle of Wight)"
author: "Student 12345"
format: docx
format: gfm
# for html output:
# output:
#   html_document:
#     number_sections: true
# for pdf output:
# bibliography: tds.bib
---

# Statement {-}

```
TRAN5340M
Transport Data Science
Assignment Title:	Add your own
Student ID: Add your ID
Word Count:	xxxx	
Lecturer: Dr Robin Lovelace
Submission Date:		
Semester:				
Academic Year: 		202425
Generative AI Category: AMBER
```


Use of Generative Artificial Intelligence (Gen AI) in this assessment. Remove statement as appropriate:

I have made no use of Gen AI

I have used Gen AI only for the specific purposes outlined in my acknowledgements


By submitting the work to which this sheet is attached you confirm your compliance with the University’s definition of Academic Integrity as: “a commitment to good study practices and shared values which ensures that my work is a true expression of my own understanding and ideas, giving credit to others where their work contributes to mine”. Double-check that your referencing and use of quotations is consistent with this commitment. 

\newpage

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, eval = TRUE)
```

# Guidance {-}

<!-- This template contains information and suggested headings for the TDS module.
It is based on an RMarkdown file. See the source code here: https://github.com/ITSLeeds/TDS/blob/master/coursework-template.Rmd .
Do not submit coursework that contains this note or any text (other than the headings) from this template.
It is just designed to get you started.  -->

You will submit the source code as a .qmd or .Rmd file, optionally included in a .zip file if you want to include data, and the resulting PDF document as your coursework submission.

As outlined in the module catalogue, the coursework should be a maximum of 10 pages long, excluding references and appendices (you should include your best work and think about maximising the use of space - the chunk option `out.width="50%"`, for example, can help with this as outlined [here](https://bookdown.org/yihui/bookdown/figures.html) )

An example of a good submission can be found here (requires a University of Leeds login): https://leeds365.sharepoint.com/sites/msteams_cbf52a/Shared%20Documents/General/stats19-example.zip

The information below provides guidance on the coursework. 

<!-- ## Two pager

- Deadline for non-assessed submission of a .zip file containing a 1 or 2 page pdf document with ideas before the final submission. The document will allow you to ask questions (e.g. "does this sound like a reasonable input dataset and topic?") and describe progress on reading in input datasets and the analysis plan. The document will contain:
  - A draft title of your topic
  - The main dataset that you will use and other datasets that you could use
  - Ideas on a research question
  - Questions you would like to ask about the topic, e.g. 'is this a suitable dataset?'
  - 2 or more references to the academic literature related to the topic
  - Any preliminary analysis you have done
  - The structure of the document could include
    - Topics considered
    - Input datasets
    - Analysis plan - I suggest creating a workflow diagram for this, e.g. as presented [here](https://user-images.githubusercontent.com/1825120/127524923-7d9f5511-84a6-430b-8de9-a603a5524f39.png)
    - Motivation for choosing this topic
    - Questions and options -->

<!-- ## Final submission -->
## Resit submission

- Deadline: TBC
- Format: a PDF file (max 10 pages, max word count of 3000 excluding tables, code, references, captions) and an .Rmd or .qmd file in a .zip file containing the Rmd file and minimal dataset needed to reproduce the results if possible (40 MB max size)
- Template: You can download a template .Rmd file as the basis of your submission: https://github.com/ITSLeeds/TDS/raw/master/coursework-template.Rmd

For the coursework you will submit a pdf a document with a maximum of 10 pages that contains code and results demonstrating your transport data science skills.

You should submit you work in  .zip file containing everything needed to reproduce the results: https://github.com/ITSLeeds/TDS/releases/download/0.20.1/coursework-template.zip

## Choosing a topic and writing your coursework

You will need to choose a topic, one or more datasets to analyse and research questions for the 10 page coursework report.
**Note: the topic must be entirely different from the one you chose for the first coursework.**

Designing and writing a good data science project involves many stages, not just writing and and knitting an Rmd document reporting data analysis methods and results.
The process involves:

- Brainstorming: what kind of topics and research questions are you interested in?
- Dataset identification: what datasets are available on the topic? If there are not good datasets related to the topic you may want to rethink your topic.
- Research questions: what questions do you want to know
- Data processing: what did you do to read-in the data?
- Exploratory data analysis: visualisation, describing the data
- Modelling/communication

As in real world data science work, there are many options to choose from.
You should decide on a topic based on your personal interest and the availability of a good dataset.
You can choose from and adapt one of the following options or choose a topic of your own.

### Topics

- Data collection and analysis
  - What is the relationship between travel behaviour (e.g. as manifested in origin-destination data represented as desire lines, routes and route networks) and road traffic casualties in a transport region (e.g. London, West Midlands and other regions in the `pct::pct_regions$region_name` data)
  - Analysis of a large transport dataset, e.g. https://www.nature.com/articles/sdata201889
- Infrastructure and travel behaviour
  - What are the relationships between specific types of infrastructure and travel, e.g. between fast roads and walking?
  - How do official sources of infrastructure data (e.g. the [CID](https://github.com/PublicHealthDataGeek/CycleInfraLnd/)) compare with crowd-sourced datasets such as OpenStreetMap (which can be accessed with the new [`osmextract` R package](https://github.com/ropensci/osmextract))
  - Using new data sources to support transport planning, e.g. using data from https://telraam.net/ or https://dataforgood.facebook.com/dfg/tools/high-resolution-population-density-maps 

- Changing transport systems
  - Modelling change in transport systems, e.g. by comparing before/after data for different countries/cities, which countries had the hardest lockdowns and where have changes been longer term? - see here for open data: https://github.com/ActiveConclusion/COVID19_mobility
  - How have movement patterns changed during the Coronavirus pandemic and what impact is that likely to have long term (see [here](https://saferactive.github.io/trafficalmr/articles/report3.html) for some graphics on this)
  
- Software development
  - Creating a package to make a particular data source more accessible, see https://github.com/ropensci/stats19 and https://github.com/elipousson/crashapi examples
  - Integration between R and A/B Street - see https://github.com/a-b-street/abstr
  
- Road safety - how can we makes roads and transport systems in general safer?
  - Influence of Road Infrastructure: 
    - 1. Assessing the role of well-designed pedestrian crossings, roundabouts, and traffic calming measures in preventing road accidents. 
    - 2. Investigating the correlation between road surface quality (e.g., potholes, uneven surfaces) and the frequency of accidents.
  - Influence of Traffic Management: 
    - 1. Assessing the role of traffic lights and speed cameras in preventing road accidents. 
    - 2. Investigating the correlation between the frequency of accidents and the presence of traffic calming measures (e.g., speed bumps, chicanes, road narrowing, etc.).
  - Legislation and Enforcement:
    - 1. Assessing the role of speed limits in preventing road accidents.

- Traffic congestion - how can we reduce congestion?
  - Data Collection and Analysis:
    - 1. Utilizing real-time traffic data from platforms like Waze and Google Maps to forecast congestion patterns.
    - 2. Analyzing historical traffic data to identify recurring congestion patterns and anticipate future traffic bottlenecks.
  - Machine Learning and Predictive Modeling:
    - 1. Designing machine learning models that use past and current traffic data to predict future congestion levels.
  
- Other
  - Other topics are welcome
  
### Datasets 

You should choose the main dataset that you will use for the coursework based on the topic and the availability of datasets. If you are interested in a particular dataset that could help you decide a topic. Good datasets include:

- STATS19 road crash data (other countries have other datasets), e.g. using data from the `stats19` package: https://docs.ropensci.org/stats19/
- 'PCT' data from UK travel behaviour - see https://itsleeds.github.io/pct/
- OpenStreetMap data (global, you will need to think of a subset by area/type), e.g. from the https://docs.ropensci.org/osmextract/index.html package
- Traffic count data, e.g. from the DfT, as described here: https://github.com/ITSLeeds/dftTrafficCounts
- Open data from a single city, e.g. Seattle: https://data-seattlecitygis.opendata.arcgis.com/
- See here: https://github.com/awesomedata/awesome-public-datasets#transportation
- And here: https://github.com/CUTR-at-USF/awesome-transit
- and [here](https://github.com/ITSLeeds/opentransportdata)

### Specific coursework options

If you are struggling for ideas and example code, these resources, in addition to the links provided in the lectures and practicals can help:

If this is a resit you must choose a different topic.

<!-- 1. Work through the stats19 training vignette to sharpen your R skills: https://docs.ropensci.org/stats19/articles/stats19-training.html -->

<!-- 2. Take a look at the Model Basics chapter (and the next if interested) of the book R for Data Science: https://r4ds.had.co.nz/model-basics.html -->

<!-- 3. Try to reproduce the results presented in the ML practical: https://github.com/ITSLeeds/TDS/blob/master/practicals/9-ml.md -->

<!-- When working on the homework you should be thinking about the datasets that you want to use for your coursework assignment. Ideas for datasets that you could use are: -->

You could pick one of these topics:

- What explanatory variables best predict the level of walking in Leeds (or a different English city), and how do walking levels relate to pedestrian safety? You could use the command `pct::get_desire_lines(region = "west-yorkshire")` to get data on walking desire lines and `get_stats19()` to get road crash data for Leeds. In terms of the topics covered in the lectures you could:
  - Show understanding of data science in context with a brief introduction that touches on the definition of transport data science
  - Demonstrate understanding of data structures by converting from a data frame of road crashes to an sf object
  - Show routes, e.g. by getting route data with `pct::get_pct_routes_fast()`
  - Show your data visualisation skills by visualising the datasets
  - Demonstrate understanding of modelling with a simple model to explain why the rate of walking varies, e.g. with the distance of the trip and variables that you will calculate (e.g. distance from the city centre)

- What factors are associated with low levels of walking and cycling and high road traffic casualty rates in the UK?

- How accessible are parks and other amenities for different areas of a particular city 
  - This could be done using data from OSM and perhaps official data from local government


## Report structure

The report should have a logical structure with key headings such as:

- Introduction
- Input data and data cleaning
- Exploratory data analysis
- Discussion (e.g. strengths and weaknesses)
- Conclusion (e.g. how the results could be used and next steps)
- References