FROM ghcr.io/itsleeds/tds

# Recommended working dir for binder notebooks
ENV NB_USER=jovyan
ENV NB_UID=1000
WORKDIR /home/jovyan/work

# repo2docker will copy the repository contents into the image at build time
