---
title: "Getting transport datasets with R"
toc: true
execute: 
  cache: true
  #eval: true
  warning: false
  message: false
bibliography: ../tds.bib
#jupyter: python3
engine: knitr
---

# Review Homework

You should now be familiar with the basics of R and the structure of transport datasets, having completed the [homework](https://itsleeds.github.io/tds/p1/#homework) from the previous session.

# Prerequisites

Note: you may need to install the `pct` package as follows:

```
remotes::install_github("ITSLeeds/pct")
```

# Getting started with GIS in R

Note that this practical builds on content in [Geocomputation with R](https://r.geocompx.org). 

# Getting OpenStreetMap data

Work through the reproducible code in the "Introducing osmextract" vignette hosted at [https://docs.ropensci.org/osmextract/articles/osmextract.html](https://docs.ropensci.org/osmextract/articles/osmextract.html).

# Getting road traffic casualty data

Work through the reproducible code in the ["Getting started with stats19" vignette hosted at docs.ropensci.org/stats19](https://docs.ropensci.org/stats19/articles/stats19.html).

# Getting started with open access origin-destination data

- Take a read of and try to reproduce the code in the [vignette "An introduction to origin-destination data"](https://cran.r-project.org/web/packages/od/vignettes/od.html) for the `od` package.
<!-- https://itsleeds.github.io/pct/articles/pct.html -->
- Import some OD data using the `pct` package, as documented at [itsleeds.github.io/pct](https://itsleeds.github.io/pct/articles/pct.html).

# Homework

1. Download and visualise 3 transport-related datasets of your choice and save the results in a reproducible .qmd file.
    - Bonus: generate a .pdf document showing the results.

