---
bibliography: ../tds.bib
---


Dear Students and aspiring Data Scientists,

Welcome to Transport Data Science.
In this module you will learn data science skills and how to apply them to solve real world problems, with a focus on transport planning.
Transport is by definition a geographic phenomenon, meaning the movement from one place to another:
"the purpose of transportation is to overcome space" [@rodrigue_geography_2013].

Becoming good at transport data science therefore means becoming good at data science in general and geographic data science in particular.
2021 is an exciting time to be learning data science for transport applications.
A wide range of new and open source tools, combined with unprecedented amounts of new data, enable researchers to visualise/model/understand transport systems in more breadth and depth than ever before [@lovelace_open_2021].

Based on an understanding of the evolving nature of data science as a collaborative and open source code-driven enterprise, this module takes a 'learning by doing' approach.
The contact time will consist of lectures 

You will need to work hard to become a proficient data scientist in the transport domain.
T

