---
format: gfm
---

# Message sent in 2024 on use of AI in the module


Hi all, 

This is just a message to say that the assessment has been categorised as "amber" in terms of AI, as highlighted in the attached coversheet (in docx and pdf format, and in the coursework template which can be found at https://github.com/ITSLeeds/TDS/blob/master/coursework-template.Rmd and a PDF version of which can be found attached).

Using the template should save you time: no need to combine PDFs because the coversheet is already included in the template. Note: the 10 page limit is for the main body of the report, and does not include the coversheet, references, or appendices.

Please do ensure that you are progressing on your coursework: you should be adding content to your .Rmd files and then knitting them to PDFs to check that they look as you expect. Do not leave this to the last minute, as it can be time-consuming to fix issues with the formatting.

Any questions, just let me know via email, on Teams, or on GitHub.

All the best,

Robin

P.s. see below the details of the categorisation of the assessment as "amber" in terms of AI.

Under this the amber category, AI tools can be used in this assessment in an assistive role for the specifically defined processes.   

In this assessment, AI tools CAN be utilised in an assistive role to:   

- Act as a support tutor to aid in the research of a topic.
- Testing and debugging of any code you produce yourself as part of the assignment.  
- Draft and structure your piece of work once you have worked through the problem.  
- Provide ideas or inspiration to help you overcome a creative block.  
- Give feedback on content or provide proof reading of content that you have generated yourself.  

In this assessment, AI tools CANNOT be utilised to:   

- For any other functions beyond those listed above. In particular, you must not use Gen AI to produce any of the final text, or other content, that you submit for assessment.

The use of Generative AI must be acknowledged in an ‘Acknowledgements’ section of any piece of academic work where it has been used as a functional tool to assist in the process of creating academic work. The minimum requirement to include in acknowledgement:   

- Name and version of the generative AI system used (e.g. ChatGPT-4.0) 
- The publisher/company that produced the Gen AI used (e.g. Open AI) 
- URL of the AI system  
- Brief description (single sentence) of context in which the tool was used.  

The standard Academic Misconduct procedure applies for students believed to have ignored this categorisation. For detailed guidance see https://generative-ai.leeds.ac.uk/ai-and assessments/categories-of-assessments/  


