---
bibliography: ../tds.bib
output: github_document
---

<!-- message to students, 2021-01-28 -->

```{r, include=FALSE}
library(tidyverse)
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```

# Session plan for Practical 4

This is will be the 4th and penultimate practical session in the TDS module.
The final practical session on coursework will be **next Friday 26th**.

The session will be structured as follows:

- Demonstration of visualisation techniques and modelling: 30 minutes (30 min)

- Working through the questions in the visualisation practical at https://github.com/ITSLeeds/TDS/blob/master/practicals/7-viz.md (25 min) 

- 5 minute break

- Breakout rooms on specific topics, 30 minutes each in any 2 of the following, in ascending order of difficulty:

  - Basic R questions and skills
    - Do you have general R questions like "Why can't I read-in this dataset"? How to do I clean this dataset? This is the room for asking general R questions.
  - Using RMarkdown for your coursework
    - In this room, which I recommend everyone visits unless you are confident with your topic and RMarkdown, you will see how to make RMarkdown documents and get a chance to present your own RMarkdown document, a vital step towards submitting the coursework
  - Visualisation
    - Further support on data visualisation
  - Modelling
    - Techniques for modelling transport data
  
# Homework

Before the session on Thursday you must create a small RMarkdown document that you can convert to PDF, either by printing to PDF in a web browser such as Chrome or by using output: pdf_document as outlined here: https://bookdown.org/yihui/rmarkdown/pdf-document.html

Bonus: try to reproduce the coursework template by copying this text into a file called test.Rmd and knitting it: https://raw.githubusercontent.com/ITSLeeds/TDS/master/coursework-template.Rmd

