---
bibliography: ../tds.bib
output: github_document
---

<!-- message to students, 2021-01-28 -->

```{r, include=FALSE}
library(tidyverse)
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```

# Session plan for Practical 5

The main purpose of this session is to support you on the project submission on May 14th.
See here for a reminder of the mark scheme: https://github.com/ITSLeeds/TDS/blob/master/coursework-template.md#marks

See here for an example of good practice submission that we will talk about: https://leeds365.sharepoint.com/sites/msteams_cbf52a/Shared%20Documents/General/stats19-example.zip


This is will be the 5th and final practical session. It will be structured as follows:

- Demonstration of tips and tricks when using RMarkdown, questions, and working on the '1 pager' to be submitted on Monday (1 hour)
  - screen share and questions will be welcome
  - based on this example of a good submission https://leeds365.sharepoint.com/sites/msteams_cbf52a/Shared%20Documents/General/stats19-example.zip
  - working through reproduce document
  - **plagiarism not tolerated**
  - quality over quantity
  
- Breakout rooms in which everyone will have a chance to talk about their dissertation ideas (1 hour)
  - 1 minute each outlining the topic and follow-up questions (10 minutes)
  - What are the strongest aspects of your coursework idea so far? What are the weakest? (20 minutes discussions and questions)
  - Working through each of these questions and sketching the answers (10 minutes working alone, 20 minutes discussions and question):
    - What are the priorities over the next three weeks (break it down into 3 parts) 
    - What do you need to find more literature on?
    - What do you need more data on (you should have all the data already)?
    - What additional skills do you need (now is a good time to ask)?
    
- Discussion of options as a group, working on the '1 pager' and sharing and links to further resources (30 minutes)
