---
title: "demo rmarkdown"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# This is a heading

## Subheading

```{r}
library(tidyverse)
library(stplanr)
od_data = od_data_sample

names(od_data)
# Ctl + Shift + M
od_data_walk = od_data %>% 
  rename(walk = foot) %>% 
  filter(walk > 0) %>% 
  select(geo_code1, geo_code2, all, car_driver, walk, bicycle) %>% 
  mutate(
    proportion_walk = walk / all,
    proportion_drive = car_driver / all
  )
class(od_data)

# calculate the % of OD have at least 1 person walking?
nrow(od_data_walk) / nrow(od_data) * 100
od_data_walk_cycle = od_data_walk %>% 
  mutate(pcycle = bicycle / all)

# Exercise 3
cor(od_data_walk_cycle$proportion_walk, od_data_walk_cycle$pcycle)
plot(od_data_walk_cycle$proportion_walk, od_data_walk_cycle$pcycle)
od_data_walk_cycle %>% 
  ggplot() +
  geom_point(aes(proportion_walk, pcycle)) +
  scale_y_continuous(labels = scales::percent) +
  scale_x_continuous(labels = scales::percent) 
```

