name: Dev Container Prebuild

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  prebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prebuild dev container
        uses: devcontainers/ci@v0.3
        with:
          configFile: .devcontainer/devcontainer.json
          runCmd: echo "Prebuild complete"
