name: Pixi CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pixi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Pixi
        run: |
          curl -fsSL https://pixi.sh/install.sh | sh
          # make pixi available in PATH for following steps
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install project dependencies with pixi
        run: pixi install

      - name: Build site / render with quarto via pixi
        run: pixi run quarto render
