name: Pull Request Checks

on:
  pull_request:
    branches: [main]

jobs:
  build-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.1'
          use-public-rspm: true 

      - name: Install R Dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2

      - name: Additional Setup
        run: |
          # Install Python:
          sudo apt-get update
          sudo apt-get install python3
          sudo apt-get install python3-pip
          python3 -m pip install jupyter jupyter-cache

      - name: Build Quarto Project
        run: quarto render